-- Partnership Pipeline + CPO schema for Supabase (Postgres)
-- Converted from SQLite partnership-pipeline-schema.sql

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =============================================================================
-- BD Pipeline
-- =============================================================================

create table if not exists public.deals (
  id text primary key,
  partner_name text not null,
  sector text,
  deal_stage text,
  description text,
  archetype text not null check (archetype in ('I','II','III','IV','V','VI','VII')),
  is_repeat boolean not null default false,
  novelty_level integer not null default 1,
  revenue_potential integer not null check (revenue_potential between 1 and 3),
  strategic_fit integer not null check (strategic_fit between 1 and 3),
  effort_tier numeric not null,
  novelty_penalty integer not null default 1,
  priority_score numeric,
  queue_position integer,
  current_stage integer not null default 1,
  blocking_factor text,
  bd_owner text,
  tech_owner text,
  urgency text,
  compliance_flags text,
  triage_classification_corrected text check (triage_classification_corrected in ('I','II','III','IV','V','VI','VII')),
  triage_novelty_flag text,
  triage_response_at timestamptz,
  triage_responded_by text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_deals_queue on public.deals (queue_position);
create index if not exists idx_deals_archetype on public.deals (archetype);
create index if not exists idx_deals_stage on public.deals (current_stage);
create index if not exists idx_deals_archived on public.deals (is_archived);

create table if not exists public.stage_transitions (
  id bigint generated by default as identity primary key,
  deal_id text not null references public.deals (id) on delete cascade,
  from_stage integer,
  to_stage integer not null,
  triggered_by text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_transitions_deal on public.stage_transitions (deal_id);

create table if not exists public.archetype_library (
  id text primary key,
  name text not null,
  one_line_test text not null,
  effort_tier numeric not null,
  description text,
  standard_components jsonb,
  precedent_name text,
  precedent_template text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =============================================================================
-- CPO
-- =============================================================================

create table if not exists public.proposal_projects (
  id text primary key,
  deal_id text not null references public.deals (id),
  pipedrive_deal_url text,
  partner_name text not null,
  partner_contact text,
  country text,
  vertical text,
  owner text,
  partnership_route text check (partnership_route in (
    'Distribution Partnership',
    'Connected Customer Journey',
    'Embedded / Co-branded',
    'Strategic Institutional Partnership',
    'Other'
  )),
  commercial_model text check (commercial_model in ('A','B','C','D')),
  current_state text not null default 'not_eligible' check (current_state in (
    'not_eligible','intake','pre_flight','business_case','eligible',
    'drafting','functional_review','revision_required','approval_ready',
    'release_gate','approved_external','delivered','negotiation',
    'superseded','withdrawn'
  )),
  priority text,
  expected_revenue numeric,
  expected_aum numeric,
  expected_volume numeric,
  target_close_date date,
  executive_summary text,
  partner_value text,
  utribe_value text,
  implementation_route text,
  technical_dependencies text,
  third_party_dependencies text,
  product_dependencies text,
  implementation_timing text,
  contract_term text,
  governance_cadence text,
  escalation_route text,
  is_archived boolean not null default false,
  source text not null default 'manual' check (source in ('manual','pipedrive','bd_tracker')),
  bd_tracker_deal_ref text,
  pipedrive_deal_id text,
  external_released_at timestamptz,
  external_release_version integer default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_proposal_deal on public.proposal_projects (deal_id);
create index if not exists idx_proposal_state on public.proposal_projects (current_state);

create table if not exists public.proposal_versions (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  version integer not null,
  state_snapshot jsonb not null,
  created_by text,
  is_release boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_proposal_versions_proposal on public.proposal_versions (proposal_id);

create table if not exists public.proposal_claims_library (
  id text primary key,
  category text not null,
  claim text not null,
  evidence_url text,
  jurisdiction text default 'Global',
  status text not null default 'Pending' check (status in ('Pending','Approved','Deprecated')),
  version text default '1.0',
  effective_date date,
  review_date date,
  owner text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_claims_status on public.proposal_claims_library (status);

create table if not exists public.proposal_claims (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  claim_id text not null references public.proposal_claims_library (id),
  section text,
  custom_wording text,
  created_at timestamptz not null default now()
);

create index if not exists idx_proposal_claims_proposal on public.proposal_claims (proposal_id);

create table if not exists public.proposal_economics (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  gross_commercial_value numeric,
  gross_confidence text check (gross_confidence in ('C','E','P')),
  operating_cost numeric,
  operating_cost_confidence text check (operating_cost_confidence in ('C','E','P')),
  residual_pool numeric,
  partner_allocation numeric,
  partner_allocation_pct numeric,
  utribe_allocation numeric,
  utribe_allocation_pct numeric,
  effective_partner_pct numeric,
  effective_utribe_pct numeric,
  partner_effective_economics numeric,
  utribe_effective_economics numeric,
  base_gross numeric,
  base_operating_cost numeric,
  downside_gross numeric,
  downside_operating_cost numeric,
  upside_gross numeric,
  upside_operating_cost numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.proposal_assumptions (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  category text check (category in (
    'Commercial','Customer/Volume','Product','Technology',
    'Compliance/Legal','Partner'
  )),
  description text not null,
  confidence text check (confidence in ('C','E','P')),
  owner text,
  evidence text,
  impact text,
  status text default 'open' check (status in ('open','resolved','superseded')),
  created_at timestamptz not null default now()
);

create index if not exists idx_proposal_assumptions_proposal on public.proposal_assumptions (proposal_id);

create table if not exists public.proposal_risks (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  risk_type text check (risk_type in (
    'Regulatory','Economics','Integration','Settlement','KYC/AML',
    'Transaction Monitoring','Customer Communication','Complaints',
    'Data Privacy','Cybersecurity','Reconciliation','Claims/Disclosures'
  )),
  owner text,
  severity text check (severity in ('Low','Medium','High','Critical')),
  mitigation text,
  status text default 'open' check (status in ('open','closed','mitigated')),
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_approvals (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  function_area text check (function_area in (
    'BD','Finance_Model','Finance_Economics','Finance_Fees',
    'Product_Scope','Product_Capability','Technology_Implementation',
    'Operations','Legal_Claims','Legal_Regulatory','Legal_Risk',
    'Legal_Commercial','Marketing_Template','Marketing_Claims'
  )),
  reviewer_name text,
  status text default 'pending' check (status in ('pending','approved','rejected','clarification')),
  decision text,
  evidence_url text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_proposal_approvals_proposal on public.proposal_approvals (proposal_id);

create table if not exists public.proposal_responsibilities (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  party text not null check (party in ('UTribe','Partner','Joint','NA')),
  domain text,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_terms (
  proposal_id text primary key references public.proposal_projects (id),
  commercial_review text,
  review_data_required text,
  review_reconsideration text,
  review_approval_process text,
  recon_cadence text,
  payment_cadence text,
  dispute_window text,
  settlement_mechanism text,
  pilot_required boolean not null default false,
  pilot_target_segment text,
  pilot_duration text,
  pilot_scope text,
  pilot_success_measures text,
  pilot_decision_gate text,
  pilot_expansion_criteria text,
  exclusivity_requested boolean not null default false,
  excl_scope text,
  excl_geography text,
  excl_product text,
  excl_customer_segment text,
  excl_duration text,
  excl_performance_conditions text,
  excl_conflict_check text,
  updated_at timestamptz not null default now()
);

create table if not exists public.proposal_success_metrics (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  metric text not null,
  measurement_basis text,
  target text,
  linked_model text,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_discussion_points (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  category text check (category in (
    'Commercial','Product/Customer Journey','Technology',
    'Operations','Legal/Compliance','Strategic Roadmap'
  )),
  question text not null,
  owner text,
  due_date date,
  status text default 'open' check (status in ('open','resolved','deferred')),
  resolution text,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_conditional_modules (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  module_type text check (module_type in (
    'extended_fees','integration_economics','growth_incentives',
    'pilot','exclusivity'
  )),
  is_active boolean not null default false,
  config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.proposal_extended_fees (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  fee_name text not null,
  category text check (category in (
    'Transaction-led','Relationship/retention-led','Operational/cost recovery'
  )),
  basis text,
  confidence text check (confidence in ('C','E','P')),
  approval_status text default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_growth_tiers (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  tier_name text not null,
  measurement_threshold numeric,
  partner_economics text,
  effective_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_preflight (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  check_item text not null,
  category text check (category in ('Qualification','Stakeholders','Functional','Commercial')),
  is_checked boolean not null default false,
  checked_by text,
  checked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_audit_events (
  id bigint generated by default as identity primary key,
  proposal_id text not null references public.proposal_projects (id),
  event_type text not null,
  actor text,
  description text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_proposal_audit_proposal on public.proposal_audit_events (proposal_id);

-- =============================================================================
-- BD Prospecting
-- =============================================================================

create table if not exists public.bd_prospecting_targets (
  id text primary key,
  firm_name text not null,
  tier integer not null default 2 check (tier in (1, 2)),
  category text not null default 'Screening Queue'
    check (category in ('Category A','Category B','Category C','Hold','Screening Queue')),
  why_this_fits text,
  contact_email text,
  notes text,
  status integer not null default 1 check (status between 1 and 10),
  special_flags text,
  auto_promoted boolean not null default false,
  deal_id text,
  proposal_id text,
  bd_owner text,
  last_contacted_at timestamptz,
  next_action text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bdp_tier on public.bd_prospecting_targets (tier);
create index if not exists idx_bdp_status on public.bd_prospecting_targets (status);
create index if not exists idx_bdp_category on public.bd_prospecting_targets (category);

-- =============================================================================
-- updated_at triggers
-- =============================================================================

drop trigger if exists trg_deals_updated_at on public.deals;
create trigger trg_deals_updated_at
  before update on public.deals
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_archetype_library_updated_at on public.archetype_library;
create trigger trg_archetype_library_updated_at
  before update on public.archetype_library
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_proposal_projects_updated_at on public.proposal_projects;
create trigger trg_proposal_projects_updated_at
  before update on public.proposal_projects
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_proposal_claims_library_updated_at on public.proposal_claims_library;
create trigger trg_proposal_claims_library_updated_at
  before update on public.proposal_claims_library
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_proposal_economics_updated_at on public.proposal_economics;
create trigger trg_proposal_economics_updated_at
  before update on public.proposal_economics
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_proposal_terms_updated_at on public.proposal_terms;
create trigger trg_proposal_terms_updated_at
  before update on public.proposal_terms
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_proposal_conditional_modules_updated_at on public.proposal_conditional_modules;
create trigger trg_proposal_conditional_modules_updated_at
  before update on public.proposal_conditional_modules
  for each row execute procedure public.set_updated_at();

drop trigger if exists trg_bd_prospecting_targets_updated_at on public.bd_prospecting_targets;
create trigger trg_bd_prospecting_targets_updated_at
  before update on public.bd_prospecting_targets
  for each row execute procedure public.set_updated_at();

-- =============================================================================
-- RLS: enable on every exposed table. No anon/authenticated policies yet —
-- the Express API will use the service role (bypasses RLS). This keeps the
-- Data API closed until auth is added.
-- =============================================================================

alter table public.deals enable row level security;
alter table public.stage_transitions enable row level security;
alter table public.archetype_library enable row level security;
alter table public.proposal_projects enable row level security;
alter table public.proposal_versions enable row level security;
alter table public.proposal_claims_library enable row level security;
alter table public.proposal_claims enable row level security;
alter table public.proposal_economics enable row level security;
alter table public.proposal_assumptions enable row level security;
alter table public.proposal_risks enable row level security;
alter table public.proposal_approvals enable row level security;
alter table public.proposal_responsibilities enable row level security;
alter table public.proposal_terms enable row level security;
alter table public.proposal_success_metrics enable row level security;
alter table public.proposal_discussion_points enable row level security;
alter table public.proposal_conditional_modules enable row level security;
alter table public.proposal_extended_fees enable row level security;
alter table public.proposal_growth_tiers enable row level security;
alter table public.proposal_preflight enable row level security;
alter table public.proposal_audit_events enable row level security;
alter table public.bd_prospecting_targets enable row level security;
